"""update order types table

Revision ID: 485e45b4d1c2
Revises: 1d5b7ceedd97
Create Date: 2021-02-11 19:32:44.797231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485e45b4d1c2'
down_revision = '1d5b7ceedd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('active', sa.Integer(), nullable=False))
    order_types = sa.table('order_types',
                          sa.Column('id', sa.Integer),
                          sa.Column('name', sa.String),
                          sa.Column('active', sa.Integer)
                          )
    op.bulk_insert(order_types, [
        {'name': 'Hydraulika', 'active': 1},
        {'name': 'Remont', 'active': 1},
        {'name': 'Motoryzacja', 'active': 1},
        {'name': 'Malarz', 'active': 1},
        {'name': 'Transport', 'active': 1},
        {'name': 'Elektryk', 'active': 1}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_types', 'active')
    # ### end Alembic commands ###
