"""create password for users; create user types

Revision ID: cdbdbe658815
Revises: 7cf276001339
Create Date: 2021-02-10 18:38:06.759215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbdbe658815'
down_revision = '7cf276001339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM users WHERE 1=1;')
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('offers_contractor_id_fkey', 'offers', type_='foreignkey')
    op.drop_table('contractors')
    op.create_foreign_key(None, 'offers', 'users', ['contractor_id'], ['id'])
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_types', ['user_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_contractor_id_fkey', 'offers', 'contractors', ['contractor_id'], ['id'])
    op.create_table('contractors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contractors_pkey')
    )
    op.drop_table('user_types')
    # ### end Alembic commands ###
